language: cpp
sudo: true

os:
  - linux
    
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - qt5-default
      - qt5-qmake

before_script:
  - cmake --version
  - qmake -v

script:
  - mkdir build
  - cd build
  - mkdir $(pwd)/out
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/out ..
  - cmake --build . --target install

